/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.TrackingUrls;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.17.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TrackingUrlsRecord extends TableRecordImpl<TrackingUrlsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached TrackingUrlsRecord
     */
    public TrackingUrlsRecord() {
        super(TrackingUrls.TRACKING_URLS);
    }

    /**
     * Create a detached, initialised TrackingUrlsRecord
     */
    @ConstructorProperties({"urlId", "chatId"})
    public TrackingUrlsRecord(@Nullable Long urlId, @Nullable Long chatId) {
        super(TrackingUrls.TRACKING_URLS);

        setUrlId(urlId);
        setChatId(chatId);
    }

    /**
     * Create a detached, initialised TrackingUrlsRecord
     */
    public TrackingUrlsRecord(edu.java.domain.jooq.tables.pojos.TrackingUrls value) {
        super(TrackingUrls.TRACKING_URLS);

        if (value != null) {
            setUrlId(value.getUrlId());
            setChatId(value.getChatId());
        }
    }

    /**
     * Getter for <code>TRACKING_URLS.URL_ID</code>.
     */
    @Nullable
    public Long getUrlId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>TRACKING_URLS.URL_ID</code>.
     */
    public void setUrlId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>TRACKING_URLS.CHAT_ID</code>.
     */
    @Nullable
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>TRACKING_URLS.CHAT_ID</code>.
     */
    public void setChatId(@Nullable Long value) {
        set(1, value);
    }

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return TrackingUrls.TRACKING_URLS.URL_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return TrackingUrls.TRACKING_URLS.CHAT_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getUrlId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getUrlId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getChatId();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public TrackingUrlsRecord value1(@Nullable Long value) {
        setUrlId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackingUrlsRecord value2(@Nullable Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackingUrlsRecord values(@Nullable Long value1, @Nullable Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
