app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s


spring:
  application:
    name: scrapper
  datasource:
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "${USERNAME}"
    password: "${PASSWORD}"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
