app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  retry-config:
    back-off-type: const
    retry-ports:
      - 400
      - 500
      - 403
      - 501
    max-attempts: 2
    delay: 2s
    jitter: 0.75
  client-config:
    stack-overflow:
      api-url: "https://api.stackexchange.com"
      domain: "stackoverflow.com"
    github:
      api-url: "https://api.github.com"
      domain: "github.com"
    update-url: "http://localhost:8090/updates"
    limit: 100
    refill-limit: 20
    delay-refill: 20s


spring:

  application:
    name: scrapper
  datasource:
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  liquibase:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui