app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s


spring:

  application:
    name: scrapper
  datasource:
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  liquibase:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui