global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'scrapper'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.17.0.1:8081']
        labels:
          application: "scrapper"
  - job_name: 'bot'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '172.17.0.1:8290' ]
        labels:
          application: "bot"

