app:
  telegram-token: "${BOT_TOKEN}"
  client-config:
    limit: 100
    refill-limit: 20
    delay-refill: 20s
  retry-config:
    back-off-type: fixed
    retry-ports:
      - 400
      - 500
      - 403
      - 501
    max-attempts: 2
    delay: 2s
    jitter: 0.75
  link-client-url: "http://localhost:8080/links"
  tg-chat-client-url: "http://localhost:8080/tg-chat"
  topic:
    name: "topic"
    partitions: 10
    replicas: 1
  dead-topic:
    name: "topic_dlq"
    partitions: 10
    replicas: 1

spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: bot
  jackson:
    time-zone: UTC





server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
