/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.TrackingUrlsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackingUrls extends TableImpl<TrackingUrlsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACKING_URLS</code>
     */
    public static final TrackingUrls TRACKING_URLS = new TrackingUrls();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TrackingUrlsRecord> getRecordType() {
        return TrackingUrlsRecord.class;
    }

    /**
     * The column <code>TRACKING_URLS.URL_ID</code>.
     */
    public final TableField<TrackingUrlsRecord, Long> URL_ID = createField(DSL.name("URL_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>TRACKING_URLS.CHAT_ID</code>.
     */
    public final TableField<TrackingUrlsRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT, this, "");

    private TrackingUrls(Name alias, Table<TrackingUrlsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrackingUrls(Name alias, Table<TrackingUrlsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TRACKING_URLS</code> table reference
     */
    public TrackingUrls(String alias) {
        this(DSL.name(alias), TRACKING_URLS);
    }

    /**
     * Create an aliased <code>TRACKING_URLS</code> table reference
     */
    public TrackingUrls(Name alias) {
        this(alias, TRACKING_URLS);
    }

    /**
     * Create a <code>TRACKING_URLS</code> table reference
     */
    public TrackingUrls() {
        this(DSL.name("TRACKING_URLS"), null);
    }

    public <O extends Record> TrackingUrls(Table<O> child, ForeignKey<O, TrackingUrlsRecord> key) {
        super(child, key, TRACKING_URLS);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<UniqueKey<TrackingUrlsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_232);
    }

    @Override
    @NotNull
    public List<ForeignKey<TrackingUrlsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_2, Keys.CONSTRAINT_23);
    }

    private transient Url _url;
    private transient Chat _chat;

    /**
     * Get the implicit join path to the <code>PUBLIC.URL</code> table.
     */
    public Url url() {
        if (_url == null)
            _url = new Url(this, Keys.CONSTRAINT_2);

        return _url;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null)
            _chat = new Chat(this, Keys.CONSTRAINT_23);

        return _chat;
    }

    @Override
    @NotNull
    public TrackingUrls as(String alias) {
        return new TrackingUrls(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public TrackingUrls as(Name alias) {
        return new TrackingUrls(alias, this);
    }

    @Override
    @NotNull
    public TrackingUrls as(Table<?> alias) {
        return new TrackingUrls(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackingUrls rename(String name) {
        return new TrackingUrls(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackingUrls rename(Name name) {
        return new TrackingUrls(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackingUrls rename(Table<?> name) {
        return new TrackingUrls(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
