/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.records;


import edu.java.scrapper.domain.jooq.tables.TrackingUrls;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackingUrlsRecord extends UpdatableRecordImpl<TrackingUrlsRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TRACKING_URLS.ID</code>.
     */
    public void setId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TRACKING_URLS.ID</code>.
     */
    @Nullable
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRACKING_URLS.URL_ID</code>.
     */
    public void setUrlId(@Nullable Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TRACKING_URLS.URL_ID</code>.
     */
    @Nullable
    public Integer getUrlId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TRACKING_URLS.CHAT_ID</code>.
     */
    public void setChatId(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TRACKING_URLS.CHAT_ID</code>.
     */
    @Nullable
    public Integer getChatId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return TrackingUrls.TRACKING_URLS.ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return TrackingUrls.TRACKING_URLS.URL_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return TrackingUrls.TRACKING_URLS.CHAT_ID;
    }

    @Override
    @Nullable
    public Integer component1() {
        return getId();
    }

    @Override
    @Nullable
    public Integer component2() {
        return getUrlId();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getChatId();
    }

    @Override
    @Nullable
    public Integer value1() {
        return getId();
    }

    @Override
    @Nullable
    public Integer value2() {
        return getUrlId();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getChatId();
    }

    @Override
    @NotNull
    public TrackingUrlsRecord value1(@Nullable Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackingUrlsRecord value2(@Nullable Integer value) {
        setUrlId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackingUrlsRecord value3(@Nullable Integer value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackingUrlsRecord values(@Nullable Integer value1, @Nullable Integer value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackingUrlsRecord
     */
    public TrackingUrlsRecord() {
        super(TrackingUrls.TRACKING_URLS);
    }

    /**
     * Create a detached, initialised TrackingUrlsRecord
     */
    @ConstructorProperties({ "id", "urlId", "chatId" })
    public TrackingUrlsRecord(@Nullable Integer id, @Nullable Integer urlId, @Nullable Integer chatId) {
        super(TrackingUrls.TRACKING_URLS);

        setId(id);
        setUrlId(urlId);
        setChatId(chatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TrackingUrlsRecord
     */
    public TrackingUrlsRecord(edu.java.scrapper.domain.jooq.tables.pojos.TrackingUrls value) {
        super(TrackingUrls.TRACKING_URLS);

        if (value != null) {
            setId(value.getId());
            setUrlId(value.getUrlId());
            setChatId(value.getChatId());
            resetChangedOnNotNull();
        }
    }
}
