/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Chat;
import edu.java.scrapper.domain.jooq.tables.TrackingUrls;
import edu.java.scrapper.domain.jooq.tables.Url;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>TRACKING_URLS</code>.
     */
    public static final TrackingUrls TRACKING_URLS = TrackingUrls.TRACKING_URLS;

    /**
     * The table <code>URL</code>.
     */
    public static final Url URL = Url.URL;
}
