/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.TrackingUrls;
import edu.java.domain.jooq.tables.Url;
import edu.java.domain.jooq.tables.records.ChatRecord;
import edu.java.domain.jooq.tables.records.TrackingUrlsRecord;
import edu.java.domain.jooq.tables.records.UrlRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.17.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1F = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1F"), new TableField[]{Chat.CHAT.ID}, true);
    public static final UniqueKey<ChatRecord> CONSTRAINT_1F8 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1F8"), new TableField[]{Chat.CHAT.TG_CHAT_ID}, true);
    public static final UniqueKey<TrackingUrlsRecord> CONSTRAINT_232 = Internal.createUniqueKey(TrackingUrls.TRACKING_URLS, DSL.name("CONSTRAINT_232"), new TableField[]{TrackingUrls.TRACKING_URLS.URL_ID, TrackingUrls.TRACKING_URLS.CHAT_ID}, true);
    public static final UniqueKey<UrlRecord> CONSTRAINT_1 = Internal.createUniqueKey(Url.URL, DSL.name("CONSTRAINT_1"), new TableField[]{Url.URL.ID}, true);
    public static final UniqueKey<UrlRecord> CONSTRAINT_14 = Internal.createUniqueKey(Url.URL, DSL.name("CONSTRAINT_14"), new TableField[]{Url.URL.URL_}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TrackingUrlsRecord, UrlRecord> CONSTRAINT_2 = Internal.createForeignKey(TrackingUrls.TRACKING_URLS, DSL.name("CONSTRAINT_2"), new TableField[]{TrackingUrls.TRACKING_URLS.URL_ID}, Keys.CONSTRAINT_1, new TableField[]{Url.URL.ID}, true);
    public static final ForeignKey<TrackingUrlsRecord, ChatRecord> CONSTRAINT_23 = Internal.createForeignKey(TrackingUrls.TRACKING_URLS, DSL.name("CONSTRAINT_23"), new TableField[]{TrackingUrls.TRACKING_URLS.CHAT_ID}, Keys.CONSTRAINT_1F, new TableField[]{Chat.CHAT.ID}, true);
}
